'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ChineseS
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BEM.ChineseS", GetType(ChineseS).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 旧 {0} 己被备分 并储存了新{0}..
        '''</summary>
        Friend Shared ReadOnly Property s_backed_up() As String
            Get
                Return ResourceManager.GetString("s_backed_up", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 你更改了档案, 请先储存.{0}{0},如果你不储存，按 OK 再载入新的档案..
        '''</summary>
        Friend Shared ReadOnly Property s_changes_to_file() As String
            Get
                Return ResourceManager.GetString("s_changes_to_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 你肯定要删除这个过滤器吗？.
        '''</summary>
        Friend Shared ReadOnly Property s_confirm_delete_filter() As String
            Get
                Return ResourceManager.GetString("s_confirm_delete_filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 你肯定要删除这个关键字吗?.
        '''</summary>
        Friend Shared ReadOnly Property s_confirm_delete_keyword() As String
            Get
                Return ResourceManager.GetString("s_confirm_delete_keyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 找不到 &quot;&quot;{0}.txt&quot;&quot;. 确定你是在你的伺服器由BattlEye目录开启这个档案..
        '''</summary>
        Friend Shared ReadOnly Property s_could_not_open_file() As String
            Get
                Return ResourceManager.GetString("s_could_not_open_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 完成!.
        '''</summary>
        Friend Shared ReadOnly Property s_done() As String
            Get
                Return ResourceManager.GetString("s_done", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 修改了..
        '''</summary>
        Friend Shared ReadOnly Property s_edited() As String
            Get
                Return ResourceManager.GetString("s_edited", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 不能储存. 发生了错误:{0}{0}{1}.
        '''</summary>
        Friend Shared ReadOnly Property s_failed_backed_up() As String
            Get
                Return ResourceManager.GetString("s_failed_backed_up", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 文件有一些反斜线可能要被跳脱, 你修改了吗?.
        '''</summary>
        Friend Shared ReadOnly Property s_fix_backslash() As String
            Get
                Return ResourceManager.GetString("s_fix_backslash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 选择了的档案已被汇入. 请记得要储存..
        '''</summary>
        Friend Shared ReadOnly Property s_items_imported() As String
            Get
                Return ResourceManager.GetString("s_items_imported", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 最新版本.
        '''</summary>
        Friend Shared ReadOnly Property s_latest_version() As String
            Get
                Return ResourceManager.GetString("s_latest_version", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 在载入这档案途中有错误, 那个是个BattleEye档案吗?.
        '''</summary>
        Friend Shared ReadOnly Property s_loading_error() As String
            Get
                Return ResourceManager.GetString("s_loading_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 你要输入一个关键字. 如果你想要一个空白的关键字, 请输入.
        '''</summary>
        Friend Shared ReadOnly Property s_need_keyword() As String
            Get
                Return ResourceManager.GetString("s_need_keyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 你要先选择一种例外..
        '''</summary>
        Friend Shared ReadOnly Property s_need_to_exception_type() As String
            Get
                Return ResourceManager.GetString("s_need_to_exception_type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 您要先选择一种记录..
        '''</summary>
        Friend Shared ReadOnly Property s_need_to_logging_type() As String
            Get
                Return ResourceManager.GetString("s_need_to_logging_type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 你要先开一个档案..
        '''</summary>
        Friend Shared ReadOnly Property s_need_to_open_file() As String
            Get
                Return ResourceManager.GetString("s_need_to_open_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 您要先选择一个过滤器..
        '''</summary>
        Friend Shared ReadOnly Property s_need_to_select_filter() As String
            Get
                Return ResourceManager.GetString("s_need_to_select_filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 您要先选择一行..
        '''</summary>
        Friend Shared ReadOnly Property s_need_to_select_line() As String
            Get
                Return ResourceManager.GetString("s_need_to_select_line", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 您要输入一个数值..
        '''</summary>
        Friend Shared ReadOnly Property s_need_value() As String
            Get
                Return ResourceManager.GetString("s_need_value", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 找不到任何档案..
        '''</summary>
        Friend Shared ReadOnly Property s_no_files_found() As String
            Get
                Return ResourceManager.GetString("s_no_files_found", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 这个档案没有任何纪录..
        '''</summary>
        Friend Shared ReadOnly Property s_no_log() As String
            Get
                Return ResourceManager.GetString("s_no_log", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 这列表比脚本的运作模式不同.{0}{0}我们会把你选择的都加入例外, 但是有些关键字可能会被删去..
        '''</summary>
        Friend Shared ReadOnly Property s_not_scripts() As String
            Get
                Return ResourceManager.GetString("s_not_scripts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 抱歉，BEM还未有能力汇入这个记录文件. 真的很抱歉..
        '''</summary>
        Friend Shared ReadOnly Property s_not_supported() As String
            Get
                Return ResourceManager.GetString("s_not_supported", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 您还未选择任何东西去汇入..
        '''</summary>
        Friend Shared ReadOnly Property s_nothing_to_import() As String
            Get
                Return ResourceManager.GetString("s_nothing_to_import", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 处理中.
        '''</summary>
        Friend Shared ReadOnly Property s_processing() As String
            Get
                Return ResourceManager.GetString("s_processing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 扫描中.
        '''</summary>
        Friend Shared ReadOnly Property s_scanning() As String
            Get
                Return ResourceManager.GetString("s_scanning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 这个纪录档案超过五万行.只会扫描头五万行..
        '''</summary>
        Friend Shared ReadOnly Property s_too_long() As String
            Get
                Return ResourceManager.GetString("s_too_long", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 无法开启BEM. 请确定能达到这两个要求:{0}{0}- 你是在BattlEye 文件夹开启BEM.{0}- 你最少运行一次ArmA 3 伺服器..
        '''</summary>
        Friend Shared ReadOnly Property s_unable_to_launch() As String
            Get
                Return ResourceManager.GetString("s_unable_to_launch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 更新档案.
        '''</summary>
        Friend Shared ReadOnly Property s_update_application() As String
            Get
                Return ResourceManager.GetString("s_update_application", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 这个电邮地址不存在. 你打错字了吧？.
        '''</summary>
        Friend Shared ReadOnly Property s_upload_email() As String
            Get
                Return ResourceManager.GetString("s_upload_email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 为了可以令BEM更上一层楼，请告诉我们什么地方出问题. 谢谢了！！！（笑 .
        '''</summary>
        Friend Shared ReadOnly Property s_upload_explain() As String
            Get
                Return ResourceManager.GetString("s_upload_explain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 为了可以令BEM更上一层楼，请上载至少一个档案. 谢谢了！！！（笑..
        '''</summary>
        Friend Shared ReadOnly Property s_upload_one_file() As String
            Get
                Return ResourceManager.GetString("s_upload_one_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 已上载你的档案! 谢谢你上载这些档案耶! ！！！！（害羞.
        '''</summary>
        Friend Shared ReadOnly Property s_upload_thanks() As String
            Get
                Return ResourceManager.GetString("s_upload_thanks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 上载压缩档案（ZIP）中.
        '''</summary>
        Friend Shared ReadOnly Property s_upload_upload_zip() As String
            Get
                Return ResourceManager.GetString("s_upload_upload_zip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 创造压缩档案（ZIP）中.
        '''</summary>
        Friend Shared ReadOnly Property s_upload_zip() As String
            Get
                Return ResourceManager.GetString("s_upload_zip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 上载了压缩档案（ZIP）!.
        '''</summary>
        Friend Shared ReadOnly Property s_uploaded_zip() As String
            Get
                Return ResourceManager.GetString("s_uploaded_zip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 请等一等! 给一些耐性来（说笑，等多一下就可以了.
        '''</summary>
        Friend Shared ReadOnly Property s_wait() As String
            Get
                Return ResourceManager.GetString("s_wait", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 由于编写文件时出错，无法保存设置。.
        '''</summary>
        Friend Shared ReadOnly Property s_write_protect() As String
            Get
                Return ResourceManager.GetString("s_write_protect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 关于BEM.
        '''</summary>
        Friend Shared ReadOnly Property t_about() As String
            Get
                Return ResourceManager.GetString("t_about", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 增加过滤器.
        '''</summary>
        Friend Shared ReadOnly Property t_add_filter() As String
            Get
                Return ResourceManager.GetString("t_add_filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 增加关键字.
        '''</summary>
        Friend Shared ReadOnly Property t_add_keyword() As String
            Get
                Return ResourceManager.GetString("t_add_keyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 取消.
        '''</summary>
        Friend Shared ReadOnly Property t_cancel() As String
            Get
                Return ResourceManager.GetString("t_cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 检查有没有更新.
        '''</summary>
        Friend Shared ReadOnly Property t_check_for_updates() As String
            Get
                Return ResourceManager.GetString("t_check_for_updates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 请选择.
        '''</summary>
        Friend Shared ReadOnly Property t_choose() As String
            Get
                Return ResourceManager.GetString("t_choose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 请选择档案:.
        '''</summary>
        Friend Shared ReadOnly Property t_choose_file() As String
            Get
                Return ResourceManager.GetString("t_choose_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 暂时载入了.
        '''</summary>
        Friend Shared ReadOnly Property t_currently_loaded() As String
            Get
                Return ResourceManager.GetString("t_currently_loaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 捐赠（不一定要，但十分鼓励.
        '''</summary>
        Friend Shared ReadOnly Property t_donate() As String
            Get
                Return ResourceManager.GetString("t_donate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 更改过滤器.
        '''</summary>
        Friend Shared ReadOnly Property t_edit_filter() As String
            Get
                Return ResourceManager.GetString("t_edit_filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 更改关键字.
        '''</summary>
        Friend Shared ReadOnly Property t_edit_keyword() As String
            Get
                Return ResourceManager.GetString("t_edit_keyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 例外类型.
        '''</summary>
        Friend Shared ReadOnly Property t_exception_type() As String
            Get
                Return ResourceManager.GetString("t_exception_type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 闲置（不是关掉了.
        '''</summary>
        Friend Shared ReadOnly Property t_idle() As String
            Get
                Return ResourceManager.GetString("t_idle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 把选择的汇入为 .
        '''</summary>
        Friend Shared ReadOnly Property t_import_as() As String
            Get
                Return ResourceManager.GetString("t_import_as", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 从记录汇入.
        '''</summary>
        Friend Shared ReadOnly Property t_import_from_logs() As String
            Get
                Return ResourceManager.GetString("t_import_from_logs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 关键字.
        '''</summary>
        Friend Shared ReadOnly Property t_keyword() As String
            Get
                Return ResourceManager.GetString("t_keyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 有双引号（&quot;&quot;）的关键字一定要有反斜线去跳脱..
        '''</summary>
        Friend Shared ReadOnly Property t_keyword_backslash() As String
            Get
                Return ResourceManager.GetString("t_keyword_backslash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 有空格的关键字一定要在双引号（&quot;&quot;）里面..
        '''</summary>
        Friend Shared ReadOnly Property t_keyword_double_quotes() As String
            Get
                Return ResourceManager.GetString("t_keyword_double_quotes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 载入档案.
        '''</summary>
        Friend Shared ReadOnly Property t_load_file() As String
            Get
                Return ResourceManager.GetString("t_load_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 什么都没有啊. 请载入一个档案去开始..
        '''</summary>
        Friend Shared ReadOnly Property t_load_to_start() As String
            Get
                Return ResourceManager.GetString("t_load_to_start", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 纪录类型.
        '''</summary>
        Friend Shared ReadOnly Property t_logging_type() As String
            Get
                Return ResourceManager.GetString("t_logging_type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 只记录在.log 档案.
        '''</summary>
        Friend Shared ReadOnly Property t_logging_type_1() As String
            Get
                Return ResourceManager.GetString("t_logging_type_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 只记录在控制台.
        '''</summary>
        Friend Shared ReadOnly Property t_logging_type_2() As String
            Get
                Return ResourceManager.GetString("t_logging_type_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 记录在.log和控制台.
        '''</summary>
        Friend Shared ReadOnly Property t_logging_type_3() As String
            Get
                Return ResourceManager.GetString("t_logging_type_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 踢走玩家（不记录）.
        '''</summary>
        Friend Shared ReadOnly Property t_logging_type_4() As String
            Get
                Return ResourceManager.GetString("t_logging_type_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 踢走玩家（只记录在.log 档案）.
        '''</summary>
        Friend Shared ReadOnly Property t_logging_type_5() As String
            Get
                Return ResourceManager.GetString("t_logging_type_5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 踢走玩家（只记录在控制台）.
        '''</summary>
        Friend Shared ReadOnly Property t_logging_type_6() As String
            Get
                Return ResourceManager.GetString("t_logging_type_6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 踢走玩家（记录在.log和控制台）.
        '''</summary>
        Friend Shared ReadOnly Property t_logging_type_7() As String
            Get
                Return ResourceManager.GetString("t_logging_type_7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 什么档案都检测不到哦.
        '''</summary>
        Friend Shared ReadOnly Property t_no_file_selected() As String
            Get
                Return ResourceManager.GetString("t_no_file_selected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设定.
        '''</summary>
        Friend Shared ReadOnly Property t_options() As String
            Get
                Return ResourceManager.GetString("t_options", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 这参数一定要符合例外..
        '''</summary>
        Friend Shared ReadOnly Property t_parameter_match_1() As String
            Get
                Return ResourceManager.GetString("t_parameter_match_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 这参数一定要包含例外..
        '''</summary>
        Friend Shared ReadOnly Property t_parameter_match_2() As String
            Get
                Return ResourceManager.GetString("t_parameter_match_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 删去过滤器.
        '''</summary>
        Friend Shared ReadOnly Property t_remove_filter() As String
            Get
                Return ResourceManager.GetString("t_remove_filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 删去关键字.
        '''</summary>
        Friend Shared ReadOnly Property t_remove_keyword() As String
            Get
                Return ResourceManager.GetString("t_remove_keyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 储存档案.
        '''</summary>
        Friend Shared ReadOnly Property t_save_file() As String
            Get
                Return ResourceManager.GetString("t_save_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 选择所有东西.
        '''</summary>
        Friend Shared ReadOnly Property t_select_all() As String
            Get
                Return ResourceManager.GetString("t_select_all", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 取消所有选择.
        '''</summary>
        Friend Shared ReadOnly Property t_select_none() As String
            Get
                Return ResourceManager.GetString("t_select_none", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 传送！（效果音效.
        '''</summary>
        Friend Shared ReadOnly Property t_send() As String
            Get
                Return ResourceManager.GetString("t_send", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to （非必要）如果你觉得我要联络你的话, 你可以留下你的电邮地址（我不会给垃圾邮件的）.
        '''</summary>
        Friend Shared ReadOnly Property t_upload_email() As String
            Get
                Return ResourceManager.GetString("t_upload_email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 以下的档案全都会传给我. 把不想给我的档案都取消选择吧.
        '''</summary>
        Friend Shared ReadOnly Property t_upload_filelist() As String
            Get
                Return ResourceManager.GetString("t_upload_filelist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 如果你的过滤器（很不幸地）有问题, 例如它们不能正确地载入, 或者某些东西没能正确的被检测, 请用以下的表格去提交你的过滤器. 我会努力的令BEM进步的！（正能量（真的有问题才用这个，不要突然把你的过滤器给我呀） ..
        '''</summary>
        Friend Shared ReadOnly Property t_upload_intro() As String
            Get
                Return ResourceManager.GetString("t_upload_intro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 请花出一些时间写一写你的过滤器有什么问题，这会令我们有机会令BEM进步（笑.
        '''</summary>
        Friend Shared ReadOnly Property t_upload_message() As String
            Get
                Return ResourceManager.GetString("t_upload_message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 上载脚本.
        '''</summary>
        Friend Shared ReadOnly Property t_upload_scripts() As String
            Get
                Return ResourceManager.GetString("t_upload_scripts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 数值.
        '''</summary>
        Friend Shared ReadOnly Property t_value() As String
            Get
                Return ResourceManager.GetString("t_value", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 数值应该要在双引号（&quot;&quot;）里面.
        '''</summary>
        Friend Shared ReadOnly Property t_value_double_quotes() As String
            Get
                Return ResourceManager.GetString("t_value_double_quotes", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
