'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class French
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BEM.French", GetType(French).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Le fichier original {0} a été récupéré et un nouveau fichier a été sauvegardé avec succès..
        '''</summary>
        Friend Shared ReadOnly Property s_backed_up() As String
            Get
                Return ResourceManager.GetString("s_backed_up", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vous avez apporté des modifications à ce fichier, veuillez sauvegarder avant de quitter.{0}{0}Si vous ne voulez pas sauvegarder, appuyez sur OK et chargez à nouveau le nouveau fichier..
        '''</summary>
        Friend Shared ReadOnly Property s_changes_to_file() As String
            Get
                Return ResourceManager.GetString("s_changes_to_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Voulez-vous vraiment supprimer ce filtre?.
        '''</summary>
        Friend Shared ReadOnly Property s_confirm_delete_filter() As String
            Get
                Return ResourceManager.GetString("s_confirm_delete_filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Voulez-vous vraiment supprimer ce mot-clé?.
        '''</summary>
        Friend Shared ReadOnly Property s_confirm_delete_keyword() As String
            Get
                Return ResourceManager.GetString("s_confirm_delete_keyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impossible de trouver le fichier &quot;&quot;{0}.txt&quot;&quot;. Vérifiez que votre programme est bien exécuté depuis le directoire BattlEye sur votre serveur..
        '''</summary>
        Friend Shared ReadOnly Property s_could_not_open_file() As String
            Get
                Return ResourceManager.GetString("s_could_not_open_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Terminé!.
        '''</summary>
        Friend Shared ReadOnly Property s_done() As String
            Get
                Return ResourceManager.GetString("s_done", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to édité.
        '''</summary>
        Friend Shared ReadOnly Property s_edited() As String
            Get
                Return ResourceManager.GetString("s_edited", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Le fichier n&apos;a pas pu être sauvegardé. L&apos;erreur suivante est survenue:{0}{0}{1}.
        '''</summary>
        Friend Shared ReadOnly Property s_failed_backed_up() As String
            Get
                Return ResourceManager.GetString("s_failed_backed_up", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Le texte pourrait contenir des antislashs qui auraient besoin d&apos;une séquence d&apos;échappement, voulez-vous les réparer?.
        '''</summary>
        Friend Shared ReadOnly Property s_fix_backslash() As String
            Get
                Return ResourceManager.GetString("s_fix_backslash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Les objets sélectionnés ont été importés. N&apos;oubliez pas de sauvergarder vos modifications..
        '''</summary>
        Friend Shared ReadOnly Property s_items_imported() As String
            Get
                Return ResourceManager.GetString("s_items_imported", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dernière Version.
        '''</summary>
        Friend Shared ReadOnly Property s_latest_version() As String
            Get
                Return ResourceManager.GetString("s_latest_version", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Une erreur est survenue en chargeant ce fichier, s&apos;agit-il d&apos;un fichier BattlEye?.
        '''</summary>
        Friend Shared ReadOnly Property s_loading_error() As String
            Get
                Return ResourceManager.GetString("s_loading_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vous devez entrer un mot-clé. Si vous ne voulez pas de mots-clés, veuillez entrer &quot;&quot;.
        '''</summary>
        Friend Shared ReadOnly Property s_need_keyword() As String
            Get
                Return ResourceManager.GetString("s_need_keyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vous devez sélectionner un Type d&apos;Exception..
        '''</summary>
        Friend Shared ReadOnly Property s_need_to_exception_type() As String
            Get
                Return ResourceManager.GetString("s_need_to_exception_type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vous devez sélectionner un Type d&apos;Enregistrement..
        '''</summary>
        Friend Shared ReadOnly Property s_need_to_logging_type() As String
            Get
                Return ResourceManager.GetString("s_need_to_logging_type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vous devez d&apos;abord ouvrir un fichier..
        '''</summary>
        Friend Shared ReadOnly Property s_need_to_open_file() As String
            Get
                Return ResourceManager.GetString("s_need_to_open_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vous devez d&apos;abord sélectionner un filtre..
        '''</summary>
        Friend Shared ReadOnly Property s_need_to_select_filter() As String
            Get
                Return ResourceManager.GetString("s_need_to_select_filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vous devez d&apos;abord sélectionner une ligne..
        '''</summary>
        Friend Shared ReadOnly Property s_need_to_select_line() As String
            Get
                Return ResourceManager.GetString("s_need_to_select_line", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vous devez entrer une valeur..
        '''</summary>
        Friend Shared ReadOnly Property s_need_value() As String
            Get
                Return ResourceManager.GetString("s_need_value", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aucun fichier trouvé.
        '''</summary>
        Friend Shared ReadOnly Property s_no_files_found() As String
            Get
                Return ResourceManager.GetString("s_no_files_found", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vous n&apos;avez pas de journal pour ce fichier..
        '''</summary>
        Friend Shared ReadOnly Property s_no_log() As String
            Get
                Return ResourceManager.GetString("s_no_log", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cette liste fonctionne différemment d&apos;un script.{0}{0}Nous ajouterons les exceptions pour ceux que vous choisirez, mais les mots-clés pourraient très bien être supprimés dans certains cas..
        '''</summary>
        Friend Shared ReadOnly Property s_not_scripts() As String
            Get
                Return ResourceManager.GetString("s_not_scripts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Désolé, l&apos;importation de ce fichier journal n&apos;est pas supportée par BEM..
        '''</summary>
        Friend Shared ReadOnly Property s_not_supported() As String
            Get
                Return ResourceManager.GetString("s_not_supported", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vous n&apos;avez pas sélectionné de fichiers à importer..
        '''</summary>
        Friend Shared ReadOnly Property s_nothing_to_import() As String
            Get
                Return ResourceManager.GetString("s_nothing_to_import", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Traitement.
        '''</summary>
        Friend Shared ReadOnly Property s_processing() As String
            Get
                Return ResourceManager.GetString("s_processing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scan en cours.
        '''</summary>
        Friend Shared ReadOnly Property s_scanning() As String
            Get
                Return ResourceManager.GetString("s_scanning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ce fichier journal contient plus de 50,000 lignes. Seules les 50,000 premières lignes ont été scannées..
        '''</summary>
        Friend Shared ReadOnly Property s_too_long() As String
            Get
                Return ResourceManager.GetString("s_too_long", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impossible de lancer BEM pour le moment. Veuillez vous assurer que les deux conditions suivantes sont réunies:{0}{0}- Vous exécutez ce programme depuis votre dossier BattlEye.{0}- Vous avez exécuté le serveur ArmA 3 au moins une fois..
        '''</summary>
        Friend Shared ReadOnly Property s_unable_to_launch() As String
            Get
                Return ResourceManager.GetString("s_unable_to_launch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mise à Jour de l&apos;Application.
        '''</summary>
        Friend Shared ReadOnly Property s_update_application() As String
            Get
                Return ResourceManager.GetString("s_update_application", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L&apos;adresse mail que vous avez entrée n&apos;est pas valide..
        '''</summary>
        Friend Shared ReadOnly Property s_upload_email() As String
            Get
                Return ResourceManager.GetString("s_upload_email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pour m&apos;aider à améliorer BEM, veuillez donner une brève explication de votre problème..
        '''</summary>
        Friend Shared ReadOnly Property s_upload_explain() As String
            Get
                Return ResourceManager.GetString("s_upload_explain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pour m&apos;aider à améliorer BEM, veuillez choisir au moins un fichier à mettre en ligne..
        '''</summary>
        Friend Shared ReadOnly Property s_upload_one_file() As String
            Get
                Return ResourceManager.GetString("s_upload_one_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vos fichiers ont été mis en ligne! Merci d&apos;avoir contribué à améliorer BEM en soumettant vos scripts!.
        '''</summary>
        Friend Shared ReadOnly Property s_upload_thanks() As String
            Get
                Return ResourceManager.GetString("s_upload_thanks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mise en ligne du fichier ZIP.
        '''</summary>
        Friend Shared ReadOnly Property s_upload_upload_zip() As String
            Get
                Return ResourceManager.GetString("s_upload_upload_zip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Création du fichier ZIP.
        '''</summary>
        Friend Shared ReadOnly Property s_upload_zip() As String
            Get
                Return ResourceManager.GetString("s_upload_zip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fichier ZIP mis en ligne!.
        '''</summary>
        Friend Shared ReadOnly Property s_uploaded_zip() As String
            Get
                Return ResourceManager.GetString("s_uploaded_zip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stop!.
        '''</summary>
        Friend Shared ReadOnly Property s_wait() As String
            Get
                Return ResourceManager.GetString("s_wait", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impossible d&apos;enregistrer les paramètres en raison d&apos;une erreur lors de l&apos;écriture du fichier..
        '''</summary>
        Friend Shared ReadOnly Property s_write_protect() As String
            Get
                Return ResourceManager.GetString("s_write_protect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A propos.
        '''</summary>
        Friend Shared ReadOnly Property t_about() As String
            Get
                Return ResourceManager.GetString("t_about", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ajouter un filtre.
        '''</summary>
        Friend Shared ReadOnly Property t_add_filter() As String
            Get
                Return ResourceManager.GetString("t_add_filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ajouter un mot-clé.
        '''</summary>
        Friend Shared ReadOnly Property t_add_keyword() As String
            Get
                Return ResourceManager.GetString("t_add_keyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Annuler.
        '''</summary>
        Friend Shared ReadOnly Property t_cancel() As String
            Get
                Return ResourceManager.GetString("t_cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recherche de Mise à Jour.
        '''</summary>
        Friend Shared ReadOnly Property t_check_for_updates() As String
            Get
                Return ResourceManager.GetString("t_check_for_updates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choisir.
        '''</summary>
        Friend Shared ReadOnly Property t_choose() As String
            Get
                Return ResourceManager.GetString("t_choose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choisir Fichier:.
        '''</summary>
        Friend Shared ReadOnly Property t_choose_file() As String
            Get
                Return ResourceManager.GetString("t_choose_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fichiers chargés.
        '''</summary>
        Friend Shared ReadOnly Property t_currently_loaded() As String
            Get
                Return ResourceManager.GetString("t_currently_loaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Faites un don.
        '''</summary>
        Friend Shared ReadOnly Property t_donate() As String
            Get
                Return ResourceManager.GetString("t_donate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editer le filtre.
        '''</summary>
        Friend Shared ReadOnly Property t_edit_filter() As String
            Get
                Return ResourceManager.GetString("t_edit_filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editer le mot-clé.
        '''</summary>
        Friend Shared ReadOnly Property t_edit_keyword() As String
            Get
                Return ResourceManager.GetString("t_edit_keyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type d&apos;Exception.
        '''</summary>
        Friend Shared ReadOnly Property t_exception_type() As String
            Get
                Return ResourceManager.GetString("t_exception_type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inactif.
        '''</summary>
        Friend Shared ReadOnly Property t_idle() As String
            Get
                Return ResourceManager.GetString("t_idle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Importer les objets vérifiés sous.
        '''</summary>
        Friend Shared ReadOnly Property t_import_as() As String
            Get
                Return ResourceManager.GetString("t_import_as", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Importer depuis le journal.
        '''</summary>
        Friend Shared ReadOnly Property t_import_from_logs() As String
            Get
                Return ResourceManager.GetString("t_import_from_logs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mot-clé.
        '''</summary>
        Friend Shared ReadOnly Property t_keyword() As String
            Get
                Return ResourceManager.GetString("t_keyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Les mots-clés comportant des guillemets doivent être précédés d&apos;un antislash pour pouvoir déclencher la séquence d&apos;échappement..
        '''</summary>
        Friend Shared ReadOnly Property t_keyword_backslash() As String
            Get
                Return ResourceManager.GetString("t_keyword_backslash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Les mots-clés comportant des espaces doivent être contenus entre des guillemets..
        '''</summary>
        Friend Shared ReadOnly Property t_keyword_double_quotes() As String
            Get
                Return ResourceManager.GetString("t_keyword_double_quotes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Charger Fichier.
        '''</summary>
        Friend Shared ReadOnly Property t_load_file() As String
            Get
                Return ResourceManager.GetString("t_load_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aucun. Chargez un fichier pour démarrer..
        '''</summary>
        Friend Shared ReadOnly Property t_load_to_start() As String
            Get
                Return ResourceManager.GetString("t_load_to_start", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type d&apos;Enregistrement.
        '''</summary>
        Friend Shared ReadOnly Property t_logging_type() As String
            Get
                Return ResourceManager.GetString("t_logging_type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consigner sur le fichier .log uniquement.
        '''</summary>
        Friend Shared ReadOnly Property t_logging_type_1() As String
            Get
                Return ResourceManager.GetString("t_logging_type_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consigner sur la console uniquement.
        '''</summary>
        Friend Shared ReadOnly Property t_logging_type_2() As String
            Get
                Return ResourceManager.GetString("t_logging_type_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consigner sur les deux.
        '''</summary>
        Friend Shared ReadOnly Property t_logging_type_3() As String
            Get
                Return ResourceManager.GetString("t_logging_type_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kicker sans consigner sur le journal.
        '''</summary>
        Friend Shared ReadOnly Property t_logging_type_4() As String
            Get
                Return ResourceManager.GetString("t_logging_type_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kicker et consigner sur le fichier .log uniquement.
        '''</summary>
        Friend Shared ReadOnly Property t_logging_type_5() As String
            Get
                Return ResourceManager.GetString("t_logging_type_5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kicker et consigner sur la console uniquement.
        '''</summary>
        Friend Shared ReadOnly Property t_logging_type_6() As String
            Get
                Return ResourceManager.GetString("t_logging_type_6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kicker et consigner sur les deux.
        '''</summary>
        Friend Shared ReadOnly Property t_logging_type_7() As String
            Get
                Return ResourceManager.GetString("t_logging_type_7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aucun fichier détecté.
        '''</summary>
        Friend Shared ReadOnly Property t_no_file_selected() As String
            Get
                Return ResourceManager.GetString("t_no_file_selected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Options.
        '''</summary>
        Friend Shared ReadOnly Property t_options() As String
            Get
                Return ResourceManager.GetString("t_options", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Le paramètre doit correspondre précisément à l&apos;exception..
        '''</summary>
        Friend Shared ReadOnly Property t_parameter_match_1() As String
            Get
                Return ResourceManager.GetString("t_parameter_match_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Le paramètre doit contenir l&apos;exception..
        '''</summary>
        Friend Shared ReadOnly Property t_parameter_match_2() As String
            Get
                Return ResourceManager.GetString("t_parameter_match_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Supprimer le filtre.
        '''</summary>
        Friend Shared ReadOnly Property t_remove_filter() As String
            Get
                Return ResourceManager.GetString("t_remove_filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Supprimer le mot-clé.
        '''</summary>
        Friend Shared ReadOnly Property t_remove_keyword() As String
            Get
                Return ResourceManager.GetString("t_remove_keyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sauvegarder le fichier.
        '''</summary>
        Friend Shared ReadOnly Property t_save_file() As String
            Get
                Return ResourceManager.GetString("t_save_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tout sélectionner.
        '''</summary>
        Friend Shared ReadOnly Property t_select_all() As String
            Get
                Return ResourceManager.GetString("t_select_all", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tout désélectionner.
        '''</summary>
        Friend Shared ReadOnly Property t_select_none() As String
            Get
                Return ResourceManager.GetString("t_select_none", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Envoyer.
        '''</summary>
        Friend Shared ReadOnly Property t_send() As String
            Get
                Return ResourceManager.GetString("t_send", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Si vous le désirez, laissez-moi votre adresse mail si vous pensez que j&apos;ai besoin de vous contacter.
        '''</summary>
        Friend Shared ReadOnly Property t_upload_email() As String
            Get
                Return ResourceManager.GetString("t_upload_email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Les fichiers suivants vont m&apos;être transmis, veuillez décocher les objets que vous ne voulez pas envoyer.
        '''</summary>
        Friend Shared ReadOnly Property t_upload_filelist() As String
            Get
                Return ResourceManager.GetString("t_upload_filelist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Si vous rencontrez des problèmes avec des fichiers filtre qui ne chargent pas correctement ou avec des objets qui ne sont pas correctement détectés, veuillez utiliser le formulaire ci-dessous pour me soumettre vos filtres et j&apos;essaierai de voir si je peux faire en sorte que BEM fonctionne mieux pour vous! Veuillez n&apos;utiliser ce formulaire que si vous rencontrez des problèmes..
        '''</summary>
        Friend Shared ReadOnly Property t_upload_intro() As String
            Get
                Return ResourceManager.GetString("t_upload_intro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Veuillez écrire un bref message expliquant les problèmes que vous rencontrez avec vos filtres.
        '''</summary>
        Friend Shared ReadOnly Property t_upload_message() As String
            Get
                Return ResourceManager.GetString("t_upload_message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mettre en ligne des scripts.
        '''</summary>
        Friend Shared ReadOnly Property t_upload_scripts() As String
            Get
                Return ResourceManager.GetString("t_upload_scripts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Valeur.
        '''</summary>
        Friend Shared ReadOnly Property t_value() As String
            Get
                Return ResourceManager.GetString("t_value", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Les valeurs doivent être contenues entre guillemets.
        '''</summary>
        Friend Shared ReadOnly Property t_value_double_quotes() As String
            Get
                Return ResourceManager.GetString("t_value_double_quotes", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
