'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Spanish
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BEM.Spanish", GetType(Spanish).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Se ha guardado una copia del original {0} y se ha guardado el nuevo en su lugar..
        '''</summary>
        Friend Shared ReadOnly Property s_backed_up() As String
            Get
                Return ResourceManager.GetString("s_backed_up", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Has modificado este archivo; deberías guardarlo antes.{0}{0}Si no quieres guardarlo, pulsa OK y abre el nuevo archivo otra vez..
        '''</summary>
        Friend Shared ReadOnly Property s_changes_to_file() As String
            Get
                Return ResourceManager.GetString("s_changes_to_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¿Seguro que quieres eliminar este filtro?.
        '''</summary>
        Friend Shared ReadOnly Property s_confirm_delete_filter() As String
            Get
                Return ResourceManager.GetString("s_confirm_delete_filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¿Seguro que quieres eliminar esta palabra clave?.
        '''</summary>
        Friend Shared ReadOnly Property s_confirm_delete_keyword() As String
            Get
                Return ResourceManager.GetString("s_confirm_delete_keyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se ha podido encontrar el archivo «{0}.txt». Asegúrate de estar ejecutando este programa desde el directorio BattlEye de tu servidor..
        '''</summary>
        Friend Shared ReadOnly Property s_could_not_open_file() As String
            Get
                Return ResourceManager.GetString("s_could_not_open_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡Hecho!.
        '''</summary>
        Friend Shared ReadOnly Property s_done() As String
            Get
                Return ResourceManager.GetString("s_done", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to modificado.
        '''</summary>
        Friend Shared ReadOnly Property s_edited() As String
            Get
                Return ResourceManager.GetString("s_edited", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se ha podido guardar este archivo porque ha ocurrido el siguiente error:{0}{0}{1}.
        '''</summary>
        Friend Shared ReadOnly Property s_failed_backed_up() As String
            Get
                Return ResourceManager.GetString("s_failed_backed_up", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El texto contiene barras invertidas que quizá haya que «escapar». ¿Deseas hacerlo?.
        '''</summary>
        Friend Shared ReadOnly Property s_fix_backslash() As String
            Get
                Return ResourceManager.GetString("s_fix_backslash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Se han importado los elementos seleccionados. No te olvides de guardar los cambios que hagas..
        '''</summary>
        Friend Shared ReadOnly Property s_items_imported() As String
            Get
                Return ResourceManager.GetString("s_items_imported", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Última versión.
        '''</summary>
        Friend Shared ReadOnly Property s_latest_version() As String
            Get
                Return ResourceManager.GetString("s_latest_version", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Se ha producido un error mientras se cargaba este archivo. ¿Seguro que es un archivo BattlEye?.
        '''</summary>
        Friend Shared ReadOnly Property s_loading_error() As String
            Get
                Return ResourceManager.GetString("s_loading_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tienes que introducir una palabra clave. Si quieres usar un espacio como palabra clave, pulsa Enter.
        '''</summary>
        Friend Shared ReadOnly Property s_need_keyword() As String
            Get
                Return ResourceManager.GetString("s_need_keyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tienes que seleccionar un Tipo de Excepción..
        '''</summary>
        Friend Shared ReadOnly Property s_need_to_exception_type() As String
            Get
                Return ResourceManager.GetString("s_need_to_exception_type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tienes que seleccionar un Tipo de Registro..
        '''</summary>
        Friend Shared ReadOnly Property s_need_to_logging_type() As String
            Get
                Return ResourceManager.GetString("s_need_to_logging_type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tienes que abrir un archivo antes..
        '''</summary>
        Friend Shared ReadOnly Property s_need_to_open_file() As String
            Get
                Return ResourceManager.GetString("s_need_to_open_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tienes que seleccionar un filtro antes..
        '''</summary>
        Friend Shared ReadOnly Property s_need_to_select_filter() As String
            Get
                Return ResourceManager.GetString("s_need_to_select_filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tienes que seleccionar una línea antes..
        '''</summary>
        Friend Shared ReadOnly Property s_need_to_select_line() As String
            Get
                Return ResourceManager.GetString("s_need_to_select_line", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tienes que introducir un valor..
        '''</summary>
        Friend Shared ReadOnly Property s_need_value() As String
            Get
                Return ResourceManager.GetString("s_need_value", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se han encontrado archivos.
        '''</summary>
        Friend Shared ReadOnly Property s_no_files_found() As String
            Get
                Return ResourceManager.GetString("s_no_files_found", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No tienes un registro para este archivo..
        '''</summary>
        Friend Shared ReadOnly Property s_no_log() As String
            Get
                Return ResourceManager.GetString("s_no_log", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Esta lista no funciona igual que los scripts.{0}{0}Añadiremos las excepciones para los que elijas, pero las palabras claves se podrían eliminar en algunos casos..
        '''</summary>
        Friend Shared ReadOnly Property s_not_scripts() As String
            Get
                Return ResourceManager.GetString("s_not_scripts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lo sentimos, pero importar este archivo de registro BEM aún no está soportado..
        '''</summary>
        Friend Shared ReadOnly Property s_not_supported() As String
            Get
                Return ResourceManager.GetString("s_not_supported", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No has seleccionado nada que importar..
        '''</summary>
        Friend Shared ReadOnly Property s_nothing_to_import() As String
            Get
                Return ResourceManager.GetString("s_nothing_to_import", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Procesamiento.
        '''</summary>
        Friend Shared ReadOnly Property s_processing() As String
            Get
                Return ResourceManager.GetString("s_processing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Análisis.
        '''</summary>
        Friend Shared ReadOnly Property s_scanning() As String
            Get
                Return ResourceManager.GetString("s_scanning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Este registro tiene más de 50000 líneas. Solo se han analizado las primeras 50000 líneas..
        '''</summary>
        Friend Shared ReadOnly Property s_too_long() As String
            Get
                Return ResourceManager.GetString("s_too_long", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se ha podido lanzar BEM ahora mismo. Asegúrate de que se cumplen estas dos condiciones:{0}{0}- Estás ejecutando este programa desde tu carpeta BattleEye.{0}- Has ejecutado el servidor ArmA 3 al menos una vez..
        '''</summary>
        Friend Shared ReadOnly Property s_unable_to_launch() As String
            Get
                Return ResourceManager.GetString("s_unable_to_launch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Actualizar la aplicación.
        '''</summary>
        Friend Shared ReadOnly Property s_update_application() As String
            Get
                Return ResourceManager.GetString("s_update_application", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La dirección de correo que has introducido no es válida..
        '''</summary>
        Friend Shared ReadOnly Property s_upload_email() As String
            Get
                Return ResourceManager.GetString("s_upload_email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Para ayudarme a mejorar BEM, explícame brevemente (en inglés) qué es lo que no funciona..
        '''</summary>
        Friend Shared ReadOnly Property s_upload_explain() As String
            Get
                Return ResourceManager.GetString("s_upload_explain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Para ayudarme a mejorar BEM, sube al menos un archivo..
        '''</summary>
        Friend Shared ReadOnly Property s_upload_one_file() As String
            Get
                Return ResourceManager.GetString("s_upload_one_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡Se han subido tus archivos! Gracias por ayudarme a mejorar BEM enviándome tus scripts..
        '''</summary>
        Friend Shared ReadOnly Property s_upload_thanks() As String
            Get
                Return ResourceManager.GetString("s_upload_thanks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cómo subir un archivo ZIP.
        '''</summary>
        Friend Shared ReadOnly Property s_upload_upload_zip() As String
            Get
                Return ResourceManager.GetString("s_upload_upload_zip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cómo crear un archivo ZIP.
        '''</summary>
        Friend Shared ReadOnly Property s_upload_zip() As String
            Get
                Return ResourceManager.GetString("s_upload_zip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡Se ha actualizado el archivo ZIP!.
        '''</summary>
        Friend Shared ReadOnly Property s_uploaded_zip() As String
            Get
                Return ResourceManager.GetString("s_uploaded_zip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¡Espera!.
        '''</summary>
        Friend Shared ReadOnly Property s_wait() As String
            Get
                Return ResourceManager.GetString("s_wait", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se pudo guardar la configuración debido a un error al escribir el archivo..
        '''</summary>
        Friend Shared ReadOnly Property s_write_protect() As String
            Get
                Return ResourceManager.GetString("s_write_protect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sobre.
        '''</summary>
        Friend Shared ReadOnly Property t_about() As String
            Get
                Return ResourceManager.GetString("t_about", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Añadir un filtro.
        '''</summary>
        Friend Shared ReadOnly Property t_add_filter() As String
            Get
                Return ResourceManager.GetString("t_add_filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Añadir una palabra clave.
        '''</summary>
        Friend Shared ReadOnly Property t_add_keyword() As String
            Get
                Return ResourceManager.GetString("t_add_keyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancelar.
        '''</summary>
        Friend Shared ReadOnly Property t_cancel() As String
            Get
                Return ResourceManager.GetString("t_cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Buscar actualizaciones.
        '''</summary>
        Friend Shared ReadOnly Property t_check_for_updates() As String
            Get
                Return ResourceManager.GetString("t_check_for_updates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Elegir.
        '''</summary>
        Friend Shared ReadOnly Property t_choose() As String
            Get
                Return ResourceManager.GetString("t_choose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Elige un archivo:.
        '''</summary>
        Friend Shared ReadOnly Property t_choose_file() As String
            Get
                Return ResourceManager.GetString("t_choose_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cargado.
        '''</summary>
        Friend Shared ReadOnly Property t_currently_loaded() As String
            Get
                Return ResourceManager.GetString("t_currently_loaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Donar.
        '''</summary>
        Friend Shared ReadOnly Property t_donate() As String
            Get
                Return ResourceManager.GetString("t_donate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modificar filtro.
        '''</summary>
        Friend Shared ReadOnly Property t_edit_filter() As String
            Get
                Return ResourceManager.GetString("t_edit_filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modificar palabra clave.
        '''</summary>
        Friend Shared ReadOnly Property t_edit_keyword() As String
            Get
                Return ResourceManager.GetString("t_edit_keyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tipo de Excepción.
        '''</summary>
        Friend Shared ReadOnly Property t_exception_type() As String
            Get
                Return ResourceManager.GetString("t_exception_type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inactivo.
        '''</summary>
        Friend Shared ReadOnly Property t_idle() As String
            Get
                Return ResourceManager.GetString("t_idle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Importar los marcados como .
        '''</summary>
        Friend Shared ReadOnly Property t_import_as() As String
            Get
                Return ResourceManager.GetString("t_import_as", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Importar desde un registro.
        '''</summary>
        Friend Shared ReadOnly Property t_import_from_logs() As String
            Get
                Return ResourceManager.GetString("t_import_from_logs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Palabra clave.
        '''</summary>
        Friend Shared ReadOnly Property t_keyword() As String
            Get
                Return ResourceManager.GetString("t_keyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cada comilla doble dentro de una palabra clave debe ir precedida de una barra invertida..
        '''</summary>
        Friend Shared ReadOnly Property t_keyword_backslash() As String
            Get
                Return ResourceManager.GetString("t_keyword_backslash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Las palabras claves que contengan espacios deben estar escritas entre comillas dobles..
        '''</summary>
        Friend Shared ReadOnly Property t_keyword_double_quotes() As String
            Get
                Return ResourceManager.GetString("t_keyword_double_quotes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cargar un archivo.
        '''</summary>
        Friend Shared ReadOnly Property t_load_file() As String
            Get
                Return ResourceManager.GetString("t_load_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ninguno. Carga un archivo para empezar..
        '''</summary>
        Friend Shared ReadOnly Property t_load_to_start() As String
            Get
                Return ResourceManager.GetString("t_load_to_start", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tipo de registro.
        '''</summary>
        Friend Shared ReadOnly Property t_logging_type() As String
            Get
                Return ResourceManager.GetString("t_logging_type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Escribir el registro en el archivo .log.
        '''</summary>
        Friend Shared ReadOnly Property t_logging_type_1() As String
            Get
                Return ResourceManager.GetString("t_logging_type_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Escribir el registro en la consola.
        '''</summary>
        Friend Shared ReadOnly Property t_logging_type_2() As String
            Get
                Return ResourceManager.GetString("t_logging_type_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Escribir el registro en ambos.
        '''</summary>
        Friend Shared ReadOnly Property t_logging_type_3() As String
            Get
                Return ResourceManager.GetString("t_logging_type_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Expulsar sin escribir el registro.
        '''</summary>
        Friend Shared ReadOnly Property t_logging_type_4() As String
            Get
                Return ResourceManager.GetString("t_logging_type_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Expulsar y escribir el registro en el archivo .log.
        '''</summary>
        Friend Shared ReadOnly Property t_logging_type_5() As String
            Get
                Return ResourceManager.GetString("t_logging_type_5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Expulsar y escribir el registro en la consola.
        '''</summary>
        Friend Shared ReadOnly Property t_logging_type_6() As String
            Get
                Return ResourceManager.GetString("t_logging_type_6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sss.
        '''</summary>
        Friend Shared ReadOnly Property t_logging_type_7() As String
            Get
                Return ResourceManager.GetString("t_logging_type_7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se ha detectado ningún archivo.
        '''</summary>
        Friend Shared ReadOnly Property t_no_file_selected() As String
            Get
                Return ResourceManager.GetString("t_no_file_selected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opciones.
        '''</summary>
        Friend Shared ReadOnly Property t_options() As String
            Get
                Return ResourceManager.GetString("t_options", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El parámetro debe coincidir con la excepción..
        '''</summary>
        Friend Shared ReadOnly Property t_parameter_match_1() As String
            Get
                Return ResourceManager.GetString("t_parameter_match_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El parámetro debe contener la excepción..
        '''</summary>
        Friend Shared ReadOnly Property t_parameter_match_2() As String
            Get
                Return ResourceManager.GetString("t_parameter_match_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminar filtro.
        '''</summary>
        Friend Shared ReadOnly Property t_remove_filter() As String
            Get
                Return ResourceManager.GetString("t_remove_filter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eliminar palabra clave.
        '''</summary>
        Friend Shared ReadOnly Property t_remove_keyword() As String
            Get
                Return ResourceManager.GetString("t_remove_keyword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Guardar archivo.
        '''</summary>
        Friend Shared ReadOnly Property t_save_file() As String
            Get
                Return ResourceManager.GetString("t_save_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seleccionar todos.
        '''</summary>
        Friend Shared ReadOnly Property t_select_all() As String
            Get
                Return ResourceManager.GetString("t_select_all", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No seleccionar ninguno.
        '''</summary>
        Friend Shared ReadOnly Property t_select_none() As String
            Get
                Return ResourceManager.GetString("t_select_none", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enviar.
        '''</summary>
        Friend Shared ReadOnly Property t_send() As String
            Get
                Return ResourceManager.GetString("t_send", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to También puedes dejarme tu dirección de email si crees que debería ponerme en contacto contigo.
        '''</summary>
        Friend Shared ReadOnly Property t_upload_email() As String
            Get
                Return ResourceManager.GetString("t_upload_email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Se me enviarán los siguientes archivos, salvo aquellos que desmarques.
        '''</summary>
        Friend Shared ReadOnly Property t_upload_filelist() As String
            Get
                Return ResourceManager.GetString("t_upload_filelist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Si estás teniendo problemas porque tus filtros no cargan correctamente o algunos elementos no se están detectando correctamente, envíame tus filtros usando el siguiente formulario y veré qué puedo hacer para que BEM funcione mejor para ti. Por favor, usa esto solo si estás teniendo problemas..
        '''</summary>
        Friend Shared ReadOnly Property t_upload_intro() As String
            Get
                Return ResourceManager.GetString("t_upload_intro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Escribe un mensaje breve en inglés explicando qué problemas estás teniendo con tus filtros.
        '''</summary>
        Friend Shared ReadOnly Property t_upload_message() As String
            Get
                Return ResourceManager.GetString("t_upload_message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Subir scripts.
        '''</summary>
        Friend Shared ReadOnly Property t_upload_scripts() As String
            Get
                Return ResourceManager.GetString("t_upload_scripts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Valor.
        '''</summary>
        Friend Shared ReadOnly Property t_value() As String
            Get
                Return ResourceManager.GetString("t_value", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El valor debería estar escrito entre comillas dobles.
        '''</summary>
        Friend Shared ReadOnly Property t_value_double_quotes() As String
            Get
                Return ResourceManager.GetString("t_value_double_quotes", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
